name: pose-transformer
channels:
  - defaults
  - conda-forge
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=5.1
  - asttokens=2.0.5
  - backcall=0.2.0
  - ca-certificates=2023.7.22
  - comm=0.1.4
  - debugpy=1.6.7
  - decorator=5.1.1
  - entrypoints=0.4
  - executing=0.8.3
  - ipykernel=6.25.2
  - ipython=8.12.2
  - jedi=0.18.1
  - jupyter_client=7.3.4
  - jupyter_core=4.12.0
  - ld_impl_linux-64=2.38
  - libffi=3.3
  - libgcc-ng=11.2.0
  - libgomp=11.2.0
  - libsodium=1.0.18
  - libstdcxx-ng=11.2.0
  - matplotlib-inline=0.1.6
  - ncurses=6.4
  - nest-asyncio=1.5.8
  - openssl=1.1.1l
  - parso=0.8.3
  - pexpect=4.8.0
  - pickleshare=0.7.5
  - pip=23.2.1
  - prompt-toolkit=3.0.36
  - ptyprocess=0.7.0
  - pure_eval=0.2.2
  - pygments=2.15.1
  - python=3.8.5
  - python-dateutil=2.8.2
  - python_abi=3.8
  - pyzmq=25.1.0
  - readline=8.2
  - setuptools=68.0.0
  - six=1.16.0
  - sqlite=3.41.2
  - stack_data=0.2.0
  - tk=8.6.12
  - tornado=6.1
  - traitlets=5.7.1
  - typing_extensions=4.7.1
  - wcwidth=0.2.5
  - wheel=0.38.4
  - xz=5.4.2
  - zeromq=4.3.4
  - zlib=1.2.13
  - pip:
      - aiohttp==3.8.5
      - aiosignal==1.3.1
      - annotated-types==0.5.0
      - astroid==2.15.6
      - async-timeout==4.0.3
      - attrs==23.1.0
      - autocommand==2.2.2
      - base58==2.1.1
      - bash==0.6
      - bcrypt==4.0.1
      - beautifulsoup4==4.12.2
      - black==23.9.1
      - blinker==1.6.2
      - bottle==0.12.25
      - cachetools==5.3.3
      - certifi==2023.7.22
      - charset-normalizer==3.2.0
      - cheroot==10.0.0
      - cherrypy==18.8.0
      - cli-passthrough==0.1.3
      - cmake==3.27.5
      - colorama==0.4.6
      - coloredlogs==15.0.1
      - configargparse==1.7
      - configparser==6.0.0
      - coverage==7.3.1
      - cssutils==2.7.1
      - cycler==0.10.0
      - cython==3.0.10
      - dash==2.16.1
      - dash-core-components==2.0.0
      - dash-html-components==2.0.0
      - dash-table==5.0.0
      - dill==0.3.7
      - efficientnet-pytorch==0.7.1
      - exceptiongroup==1.1.3
      - fastjsonschema==2.19.1
      - ffmpeg==1.4
      - filelock==3.12.4
      - flake8==6.1.0
      - flask==2.3.3
      - flatbuffers==23.5.26
      - frozenlist==1.4.0
      - fsspec==2023.9.1
      - future==0.18.3
      - gitdb==4.0.10
      - gitpython==3.1.36
      - huggingface-hub==0.17.1
      - humanfriendly==10.0
      - idna==3.4
      - imageio==2.9.0
      - importlib-metadata==6.8.0
      - importlib-resources==6.1.0
      - inflect==7.0.0
      - iniconfig==2.0.0
      - ipywidgets==8.1.2
      - isort==5.12.0
      - itsdangerous==2.1.2
      - jaraco-collections==4.3.0
      - jaraco-context==4.3.0
      - jaraco-functools==3.9.0
      - jaraco-text==3.11.1
      - jinja2==3.1.2
      - joblib==1.3.2
      - jupyter-core==5.7.2
      - jupyterlab-widgets==3.0.10
      - kiwisolver==1.3.2
      - lazy-object-proxy==1.9.0
      - lit==16.0.6
      - mando==0.7.1
      - markupsafe==2.1.3
      - matplotlib==3.4.3
      - mccabe==0.7.0
      - more-itertools==10.1.0
      - mpmath==1.3.0
      - multidict==6.0.4
      - munch==4.0.0
      - mypy-extensions==1.0.0
      - nbformat==5.10.4
      - networkx==2.6.3
      - numpy==1.22.4
      - nuscenes-devkit==1.1.11
      - nvidia-cublas-cu11==11.10.3.66
      - nvidia-cuda-cupti-cu11==11.7.101
      - nvidia-cuda-nvrtc-cu11==11.7.99
      - nvidia-cuda-runtime-cu11==11.7.99
      - nvidia-cudnn-cu11==8.5.0.96
      - nvidia-cufft-cu11==10.9.0.58
      - nvidia-curand-cu11==10.2.10.91
      - nvidia-cusolver-cu11==11.4.0.1
      - nvidia-cusparse-cu11==11.7.4.91
      - nvidia-nccl-cu11==2.14.3
      - nvidia-nvtx-cu11==11.7.91
      - onnx==1.14.1
      - onnxruntime==1.16.1
      - open3d==0.18.0
      - opencv-python==4.8.0.76
      - packaging==23.1
      - palettable==3.3.3
      - pandas==1.3.3
      - pathspec==0.11.2
      - pillow==10.0.1
      - platformdirs==3.11.0
      - pluggy==1.3.0
      - pointnet2==0.0.0
      - portend==3.2.0
      - pretrainedmodels==0.7.4
      - protobuf==3.20.2
      - psutil==5.9.5
      - pycodestyle==2.11.0
      - pycontracts==1.8.12
      - pydantic==1.10.15
      - pydantic-core==2.6.3
      - pyflakes==3.1.0
      - pylint==2.17.5
      - pyparsing==2.4.7
      - pytest==7.4.2
      - pytest-click==1.1.0
      - pytest-cov==4.1.0
      - pytest-mock==3.11.1
      - pytest-pylint==0.19.0
      - pytz==2021.1
      - pywavelets==1.1.1
      - pyyaml==6.0.1
      - radon==6.0.1
      - requests==2.31.0
      - safetensors==0.3.3
      - schedule==1.2.0
      - scikit-image==0.18.3
      - scikit-learn==1.3.1
      - scipy==1.7.1
      - seaborn==0.12.2
      - segmentation-models-pytorch==0.3.3
      - sentry-sdk==1.30.0
      - setproctitle==1.3.2
      - shapely==1.8.5.post1
      - simplejson==3.19.1
      - smmap==5.0.0
      - soupsieve==2.5
      - sympy==1.12
      - tailer==0.4.1
      - tempora==5.5.0
      - termcolor==2.3.0
      - texttable==1.6.7
      - threadpoolctl==3.2.0
      - tifffile==2021.8.30
      - timm==0.9.2
      - tomli==2.0.1
      - tomlkit==0.12.1
      - torch==2.0.1+cu117
      - torch-scatter==2.1.2
      - torchaudio==2.0.2+cu117
      - torchvision==0.15.2+cu117
      - transforms3d==0.4.1
      - triton==2.0.0
      - unidecode==1.3.6
      - uritools==4.0.2
      - urllib3==2.0.4
      - wandb==0.15.10
      - werkzeug==2.3.7
      - widgetsnbextension==4.0.10
      - wrapt==1.15.0
      - yarl==1.9.2
      - zc-lockfile==3.0.post1
      - zipp==3.17.0
